#ifndef EXPR_H
#define EXPR_H

/* Experiments to run */

#define TEST 1
#define IDLE 2		// analyze overhead generated by an uncontested lock
#define SCAL 4		// analyze overhead generated by a contested lock
#define FAIR 8		// analyze lock scheduling policies
#define POHD 16		// analyze overhead in the firewall when using uncontested locks
#define PSCL 32		// analyze use-cases scheduling policies which will result in the best speedup

int time_counter_serial(int);
int time_counter_parallel(int, int, int);
float work_counter_serial(int);
float work_counter_parallel(int, int, int);
void packet_serial(int, int, long, int, short);
void packet_parallel(int, int, long, int, short, int, int, int);

#endif
